apt-get -qqy update
apt-get -qqy install libpq-dev python-pip python-dev postgresql postgresql-contrib git-all python-django python-psycopg2

sudo pip install --upgrade django==1.11.5
sudo pip install --upgrade psycopg2==2.7.3.1

sudo -u postgres psql -c "CREATE USER developer WITH PASSWORD 'insecurepassword';"
sudo -u postgres psql -c "ALTER ROLE developer CREATEDB;"
sudo -u postgres psql -c "CREATE DATABASE wikiserver;"

python /vagrant/researchproject/manage.py makemigrations
python /vagrant/researchproject/manage.py migrate

sudo -u postgres psql wikiserver -c "insert into auth_user(username, first_name, last_name, email, password, is_superuser, is_staff, is_active, date_joined) values('TestUser01', '', '', '', 'insecurepassword', false, false, true, 'today');"
sudo -u postgres psql wikiserver -c "insert into auth_user(username, first_name, last_name, email, password, is_superuser, is_staff, is_active, date_joined) values('TestUser02', '', '', '', 'insecurepassword', false, false, true, 'today');"

sudo -u postgres psql wikiserver -c "insert into wikiserver_page(owner_id, date_created) values('1', 'today');"
sudo -u postgres psql wikiserver -c "insert into wikiserver_page_version(title, content, date_edited) values('Lorem', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pulvinar suscipit augue, vitae auctor nisi porta sed. Pellentesque imperdiet tellus a eleifend tempor. Proin vehicula arcu id nunc pretium finibus. Praesent tincidunt est nec nisl tempor, eu rutrum purus gravida. Nunc nec erat massa. Morbi lobortis, tellus at tristique rutrum, eros nisl aliquam nulla, eu accumsan justo dui sed sem. Mauris suscipit justo est, nec aliquam sapien tempus a. Nulla fermentum ut nunc non commodo. Maecenas suscipit lorem sed ante facilisis vulputate. Maecenas iaculis nisi justo, ac accumsan augue tristique vitae. Mauris magna ex, molestie ac tellus in, mollis sollicitudin ligula. Vestibulum a mollis elit. Vivamus eu luctus est. Pellentesque consequat erat nec felis pulvinar tristique. Proin ac nunc semper, interdum magna vitae, egestas orci. Donec pulvinar odio at facilisis congue. Quisque massa risus, commodo quis accumsan non, consectetur in lectus. Donec eu velit eu ipsum ultrices dictum ut vitae neque. Cras at interdum nunc, ac sollicitudin lacus. Pellentesque porttitor maximus turpis in pretium. Suspendisse dolor eros, aliquam quis finibus ultricies, sagittis sollicitudin lorem. Sed tincidunt enim magna, ut convallis metus accumsan ut. Mauris eu libero in nibh tempus maximus. Aenean sit amet orci interdum, scelerisque eros non, placerat nisl. Duis id gravida orci. Donec eu malesuada felis. Phasellus at felis aliquam, blandit urna eu, dignissim erat. Fusce suscipit lacinia turpis ac laoreet.', 'today');"

sudo -u postgres psql wikiserver -c "insert into wikiserver_page(owner_id, date_created) values('1', 'today');"
sudo -u postgres psql wikiserver -c "insert into wikiserver_page_version(title, content, date_edited) values('Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a ligula sit amet tortor sagittis tincidunt non eu eros. Suspendisse potenti. Morbi pulvinar fringilla eros, id faucibus elit ultricies ac. Nam auctor efficitur purus convallis porttitor. Fusce lacinia nulla vel ligula mollis scelerisque. Ut iaculis porttitor commodo. Fusce nec elit orci. Donec cursus et urna id faucibus. Vivamus rutrum facilisis lorem, ac euismod diam scelerisque ac. Ut faucibus neque vel quam lacinia condimentum. Maecenas non magna non augue congue faucibus. In semper arcu ut nibh porttitor bibendum. Nulla gravida non augue ut faucibus.', 'today');"

sudo -u postgres psql wikiserver -c "insert into wikiserver_page(owner_id, date_created) values('1', 'today');"
sudo -u postgres psql wikiserver -c "insert into wikiserver_page_version(title, content, date_edited) values('Roots', 'Maecenas mauris ligula, dignissim quis sodales vitae, tincidunt sit amet ante. Nunc magna felis, aliquet vitae pretium sit amet, interdum ut erat. Nullam vehicula mollis sollicitudin. Phasellus convallis non nisl at posuere. Integer venenatis odio sed dolor cursus bibendum. Morbi aliquam risus id dapibus fringilla. Aenean aliquam vehicula tellus. Fusce porta ultricies posuere.', 'today');"

sudo -u postgres psql wikiserver -c "insert into wikiserver_page(owner_id, date_created) values('2', 'today');"
sudo -u postgres psql wikiserver -c "insert into wikiserver_page_version(title, content, date_edited) values('Dolor', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a ligula sit amet tortor sagittis tincidunt non eu eros. Suspendisse potenti. Morbi pulvinar fringilla eros, id faucibus elit ultricies ac. Nam auctor efficitur purus convallis porttitor. Fusce lacinia nulla vel ligula mollis scelerisque. Ut iaculis porttitor commodo. Fusce nec elit orci. Donec cursus et urna id faucibus. Vivamus rutrum facilisis lorem, ac euismod diam scelerisque ac. Ut faucibus neque vel quam lacinia condimentum. Maecenas non magna non augue congue faucibus. In semper arcu ut nibh porttitor bibendum. Nulla gravida non augue ut faucibus.', 'today');"

sudo -u postgres psql wikiserver -c "insert into wikiserver_page(owner_id, date_created) values('2', 'today')"
sudo -u postgres psql wikiserver -c "insert into wikiserver_page_version(title, content, date_edited) values('Trunk', 'Maecenas mauris ligula, dignissim quis sodales vitae, tincidunt sit amet ante. Nunc magna felis, aliquet vitae pretium sit amet, interdum ut erat. Nullam vehicula mollis sollicitudin. Phasellus convallis non nisl at posuere. Integer venenatis odio sed dolor cursus bibendum. Morbi aliquam risus id dapibus fringilla. Aenean aliquam vehicula tellus. Fusce porta ultricies posuere.', 'today');"

sudo -u postgres psql wikiserver -c "insert into wikiserver_page(owner_id, date_created) values('1', 'today');"
sudo -u postgres psql wikiserver -c "insert into wikiserver_page_version(title, content, date_edited) values('Mauris', 'Mauris efficitur erat ligula, vitae rhoncus erat commodo nec. Maecenas vulputate viverra ligula id scelerisque. Mauris vehicula est eu velit volutpat viverra. Aenean magna sapien, vestibulum quis sodales in, tempus vitae arcu. Suspendisse vestibulum massa vitae est viverra accumsan. Suspendisse quis arcu turpis. Proin eu est non leo tristique consequat. Etiam bibendum mauris non ligula gravida, eu porta eros venenatis. Praesent vitae odio eget ligula ultricies vehicula. Aenean vel magna aliquet, tempus neque sed, laoreet justo. Vestibulum pretium massa lorem. Sed facilisis vehicula lectus vitae fringilla. Morbi bibendum vitae nunc eu rhoncus. Maecenas commodo fringilla felis ut congue. Vivamus dapibus, lorem ac fermentum commodo, turpis lacus tincidunt ipsum, quis semper felis nisi vitae arcu. Pellentesque id nisl vitae libero venenatis imperdiet sed non metus.', 'today');"

sudo -u postgres psql wikiserver -c "insert into wikiserver_page(owner_id, date_created) values('2', 'today');"
sudo -u postgres psql wikiserver -c "insert into wikiserver_page_version(title, content, date_edited) values('Amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a ligula sit amet tortor sagittis tincidunt non eu eros. Suspendisse potenti. Morbi pulvinar fringilla eros, id faucibus elit ultricies ac. Nam auctor efficitur purus convallis porttitor. Fusce lacinia nulla vel ligula mollis scelerisque. Ut iaculis porttitor commodo. Fusce nec elit orci. Donec cursus et urna id faucibus. Vivamus rutrum facilisis lorem, ac euismod diam scelerisque ac. Ut faucibus neque vel quam lacinia condimentum. Maecenas non magna non augue congue faucibus. In semper arcu ut nibh porttitor bibendum. Nulla gravida non augue ut faucibus.', 'today');"

sudo -u postgres psql wikiserver -c "insert into wikiserver_page(owner_id, date_created) values('1', 'today');"
sudo -u postgres psql wikiserver -c "insert into wikiserver_page_version(title, content, date_edited) values('Efficitur', 'Mauris efficitur erat ligula, vitae rhoncus erat commodo nec. Maecenas vulputate viverra ligula id scelerisque. Mauris vehicula est eu velit volutpat viverra. Aenean magna sapien, vestibulum quis sodales in, tempus vitae arcu. Suspendisse vestibulum massa vitae est viverra accumsan. Suspendisse quis arcu turpis. Proin eu est non leo tristique consequat. Etiam bibendum mauris non ligula gravida, eu porta eros venenatis. Praesent vitae odio eget ligula ultricies vehicula. Aenean vel magna aliquet, tempus neque sed, laoreet justo. Vestibulum pretium massa lorem. Sed facilisis vehicula lectus vitae fringilla. Morbi bibendum vitae nunc eu rhoncus. Maecenas commodo fringilla felis ut congue. Vivamus dapibus, lorem ac fermentum commodo, turpis lacus tincidunt ipsum, quis semper felis nisi vitae arcu. Pellentesque id nisl vitae libero venenatis imperdiet sed non metus.', 'today');"

sudo -u postgres psql wikiserver -c "insert into wikiserver_page(owner_id, date_created) values('2', 'today');"
sudo -u postgres psql wikiserver -c "insert into wikiserver_page_version(title, content, date_edited) values('Maecenas', 'Maecenas mauris ligula, dignissim quis sodales vitae, tincidunt sit amet ante. Nunc magna felis, aliquet vitae pretium sit amet, interdum ut erat. Nullam vehicula mollis sollicitudin. Phasellus convallis non nisl at posuere. Integer venenatis odio sed dolor cursus bibendum. Morbi aliquam risus id dapibus fringilla. Aenean aliquam vehicula tellus. Fusce porta ultricies posuere.', 'today');"

sudo -u postgres psql wikiserver -c "insert into wikiserver_page(owner_id, date_created) values('2', 'today');"
sudo -u postgres psql wikiserver -c "insert into wikiserver_page_version(title, content, date_edited) values('Ligula', 'Maecenas mauris ligula, dignissim quis sodales vitae, tincidunt sit amet ante. Nunc magna felis, aliquet vitae pretium sit amet, interdum ut erat. Nullam vehicula mollis sollicitudin. Phasellus convallis non nisl at posuere. Integer venenatis odio sed dolor cursus bibendum. Morbi aliquam risus id dapibus fringilla. Aenean aliquam vehicula tellus. Fusce porta ultricies posuere.', 'today');"
